---
title: "Asociation Rules"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# association rules with R Groceries data

```{r}
library(arules)
library(arulesViz)
library(datasets)
data("Groceries")
# summary statistics
summary(Groceries)
inspect(head(Groceries,10))
str(Groceries)
head(Groceries)
#rules <- apriori(Groceries,parameter=list(supp = 0.001, conf=0.8))
```

# plot the first 20 'count' of each grocery item appearing in the dataset
```{r}
itemFrequencyPlot(Groceries,topN=20,type="absolute")
```

# RETRIEVAL OF ASSOCIATION RULES
Use 'apriori' to generate association rules. Output to 'rules', which is a data frame. 

```{r}
rules <- apriori(Groceries,parameter=list(supp = 0.001, conf=0.5))

#specify to two decimal places for any numeric output
options(digits=2)

# summarize the set of rules which tells the number of rules generated by length (number of items),amongst other things
inspect(rules[1:5])
summary(rules)
```

# top 3 rules along with their measures of support, confidence and lift.
```{r}
inspect(head(sort(rules, by ="support"),3))
inspect(head(sort(rules, by ="confidence"),3))
inspect(head(sort(rules, by ="lift"),3))
#generate rules where we fix some values "whole milk"  
#inspect(subset(rules, subset = lhs %pin% "whole milk"))



```

# VISUALIZATION

```{r}
#extract subsets
subrules1 <-rules[quality(rules)$confidence > 0.8]
subrules2<-head(sort(rules,by="lift"),10)
# plotting 
plot(subrules2,method="graph")
plot(subrules1,jitter = 0,engine = "plotly")
plot(subrules1,method="two-key plot")
```

